apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: oidc
 namespace: application-01
plugin: oidc
config:
  discovery: <discovery>
  bearer_only: "yes"
  introspection_endpoint: <introspection_endpoint>
  introspection_endpoint_auth_method: client_secret_post
  use_jwks: "yes"
  client_id: <client id>
  validate_scope: "false"
  bearer_jwt_auth_enable: "no"
  access_token_header_name: Authorization
  access_token_as_bearer: "yes"
  client_secret: pluto
  # redirect_uri: /
